{"name": "Получение ошибки \"Недостаточно данных для создания учетной записи\" при попытке создать курьера с незаполненным полем Password", "status": "passed", "start": 1744212963517, "stop": 1744212963714, "uuid": "ab49c0d0-cdb9-4470-841d-307ff8d6da7a", "historyId": "0d34ec20c0faffc054716bcd9786a23c", "testCaseId": "0d34ec20c0faffc054716bcd9786a23c", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_without_password_in_password_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Martin"}, {"name": "thread", "value": "15620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}