{"name": "Проверка получения ошибки \"Учетная запись не найдена\" при передачи в теле запроса неправильных данных полей логина или пароля", "status": "passed", "parameters": [{"name": "incorrectly_filled_in_fields", "value": "{'login': 'МартинMartin', 'password': '*3Jw'}"}], "start": 1744212962380, "stop": 1744212962598, "uuid": "ed64a114-0c26-442f-8243-c5b632d5cc4d", "historyId": "697d4a4299da4edb5b22a84aed073b07", "testCaseId": "a6fe86b6256607a65c10d1f15a41e383", "fullName": "tests.test_check_login_courier.TestCheckLoginCourier#test_login_courier_with_incorrect_loginor_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_login_courier"}, {"name": "subSuite", "value": "TestCheckLoginCourier"}, {"name": "host", "value": "Martin"}, {"name": "thread", "value": "15620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_login_courier"}]}