{"name": "Проверка получения ошибки \"Учетная запись не найдена\" при передачи в теле запроса неправильных данных полей логина или пароля", "status": "passed", "parameters": [{"name": "incorrectly_filled_in_fields", "value": "{'login': 'МартинMartin', 'password': '!4Lt'}"}], "start": 1744368074770, "stop": 1744368074974, "uuid": "1a428d1f-f97c-47bb-8064-fbc5b1a249e6", "historyId": "4f3b35dc167835498cfcabb39da952f3", "testCaseId": "a6fe86b6256607a65c10d1f15a41e383", "fullName": "tests.test_check_login_courier.TestCheckLoginCourier#test_login_courier_with_incorrect_loginor_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_check_login_courier"}, {"name": "subSuite", "value": "TestCheckLoginCourier"}, {"name": "host", "value": "Martin"}, {"name": "thread", "value": "29744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_check_login_courier"}]}